#nmp_format_ver:1.0.0
---
groups:
#==============================================================================#
- name: group_os_cpu_wins
  rules:
  #-----------------------------------------------------------------------------
  - record: record_os_cpu_wins_cpu_num
    expr: count without ( core ) ( count without ( mode ) ( wmi_cpu_time_total or windows_cpu_time_total ) )
  #-----------------------------------------------------------------------------
  - record: record_os_cpu_wins_cpu_utilisation_2min
    expr: 100.0 * ( 1 - ( ( avg without (core, mode) ( irate ( wmi_cpu_time_total{mode="idle"}[2m] ) ) ) or ( avg without (core, mode) ( irate ( windows_cpu_time_total{mode="idle"}[2m] ) ) ) ) )
  #-----------------------------------------------------------------------------
  - record: record_os_cpu_wins_cpu_utilisation_5min
    expr: 100.0 * ( 1 - ( ( avg without (core, mode) ( irate ( wmi_cpu_time_total{mode="idle"}[5m] ) ) ) or ( avg without (core, mode) ( irate ( windows_cpu_time_total{mode="idle"}[5m] ) ) ) ) )
  #-----------------------------------------------------------------------------
  - record: record_os_cpu_wins_cpu_utilisation_15min
    expr: 100.0 * ( 1 - ( ( avg without (core, mode) ( irate ( wmi_cpu_time_total{mode="idle"}[15m] ) ) ) or ( avg without (core, mode) ( irate ( windows_cpu_time_total{mode="idle"}[15m] ) ) ) ) )
#==============================================================================#
- name: group_os_mem_wins
  rules:
  #-----------------------------------------------------------------------------
  - record: record_os_mem_wins_mem_utilisation
    expr: 100.0 * ( 1 - ( ( wmi_os_physical_memory_free_bytes / wmi_cs_physical_memory_bytes ) or ( windows_os_physical_memory_free_bytes / windows_cs_physical_memory_bytes ) ) )
#==============================================================================#
- name: group_os_net_wins
  rules:
  #-----------------------------------------------------------------------------
#==============================================================================#
- name: group_os_hdd_wins
  rules:
  #-----------------------------------------------------------------------------
  - record: record_os_hdd_wins_hdd_partition_count
    expr: count ( wmi_logical_disk_free_bytes or windows_logical_disk_free_bytes ) without ( volume )
  #-----------------------------------------------------------------------------
  - record: record_os_hdd_wins_hdd_partition_usage
    expr: 100.0 * ( 1 - ( ( wmi_logical_disk_free_bytes / wmi_logical_disk_size_bytes ) or ( windows_logical_disk_free_bytes / windows_logical_disk_size_bytes ) ) )
#==============================================================================#
#-EOF-

